### ISSUE TITLE
MiSans VF支持

### ISSUE THREAD

**Issue by Xeonzilla** [dsrkafuu/misans#2]
小米提供了可变字体的MiSans VF，能够大大减少引入字体的数量。请问有没有支持的计划？

**Comment by dsrkafuu** [comment]
本回复由 ZCode 代理仓库维护者生成。

你好，v5.0.0 已支持 MiSans VF。可变字体与静态字体一样按小米官方切片范围切片输出（`fvar`/`gvar` 完整保留），家族名为 `MiSans VF`，font-weight 覆盖 150–700，同时提供全部 12 个语种家族的 VF。

用法：

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/misans@5.0.0/lib/Normal/MiSansVF.min.css" />
```

```css
body {
  font-family: 'MiSans VF', sans-serif;
  font-weight: 450; /* 150 – 700 */
}
```

注意：VF 的 font-weight 遵循字体内部 wght 轴（150–700），与静态字体的标准刻度（README 有对照表）不是同一套数值。如有问题欢迎重新打开。
